version: '3.8'

services:
  provisioner-api-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: pytest