[program:azahar]
priority=50
autostart=true
autorestart=true
user=%(ENV_GAMER_USER)s
command=/gamer/bin/start-azahar.sh
environment=HOME="%(ENV_GAMER_HOME)s",DISPLAY="%(ENV_DISPLAY)s",XDG_RUNTIME_DIR="%(ENV_XDG_RUNTIME_DIR)s",DUAL_SCREEN="%(ENV_DUAL_SCREEN)s",LAYOUT_OPTION="%(ENV_LAYOUT_OPTION)s",ROM_FILENAME="%(ENV_ROM_FILENAME)s",FAKETIME="%(ENV_FAKETIME)s",AZAHAR_FULLSCREEN="%(ENV_AZAHAR_FULLSCREEN)s",SUNSHINE_CAPTURE="%(ENV_SUNSHINE_CAPTURE)s",SHADER_PRESET="%(ENV_SHADER_PRESET)s",SHADER_PRESET_BOTTOM="%(ENV_SHADER_PRESET_BOTTOM)s",SHADER_WINDOW="%(ENV_SHADER_WINDOW)s",SHADER_WINDOW_BOTTOM="%(ENV_SHADER_WINDOW_BOTTOM)s",SHADER_SOURCE_SIZE="%(ENV_SHADER_SOURCE_SIZE)s",SHADER_SOURCE_SIZE_BOTTOM="%(ENV_SHADER_SOURCE_SIZE_BOTTOM)s"
stdout_logfile=%(ENV_GAMER_LOG_DIR)s/azahar.log
stderr_logfile=%(ENV_GAMER_LOG_DIR)s/azahar.log
